<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fowler" nsURI="fowler.meta" nsPrefix="org.eclipse.viatra.cep.examples.fowler.incquery.model">
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="door" lowerBound="1" eType="#//Door"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawers" upperBound="-1"
        eType="#//Drawer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wall" lowerBound="1" eType="#//Wall"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="light" lowerBound="1" eType="#//Light"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drawer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Door">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="knocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Light">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"
        defaultValueLiteral="OFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="OFF"/>
    <eLiterals name="ON" value="1"/>
  </eClassifiers>
</ecore:EPackage>
