<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cps" nsURI="org.eclipse.viatra.examples.dse.cps" nsPrefix="org.eclipse.viatra.examples.dse.cps">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.incquery.querybasedfeature org.eclipse.viatra.query.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CyberPhysicalSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationTypes" upperBound="-1"
        eType="#//ApplicationType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostTypes" upperBound="-1"
        eType="#//HostType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//ApplicationInstance" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="hu.bme.mit.inf.cps.patterns.applications"/>
      </eAnnotations>
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.viatra.dse.examples.cps.patterns.applications"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hosts" upperBound="-1"
        eType="#//HostInstance" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="hu.bme.mit.inf.cps.patterns.hosts"/>
      </eAnnotations>
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.viatra.dse.examples.cps.patterns.hosts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//Request" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationType" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//ResourceRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//ApplicationInstance" containment="true" eOpposite="#//ApplicationInstance/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostType" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//HostInstance" containment="true" eOpposite="#//HostInstance/type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultHdd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostType" lowerBound="1"
        eType="#//HostType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredHdd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationInstance" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ApplicationType"
        eOpposite="#//ApplicationType/instances"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedTo" upperBound="-1"
        eType="#//HostInstance" eOpposite="#//HostInstance/applications"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicatesWith" upperBound="-1"
        eType="#//ApplicationInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"
        defaultValueLiteral="Stopped"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostInstance" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//HostType"
        eOpposite="#//HostType/instances"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//ApplicationInstance" eOpposite="#//ApplicationInstance/allocatedTo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canCommunicateWith" upperBound="-1"
        eType="#//HostInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableHdd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalHdd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeIp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="Stopped" value="1"/>
    <eLiterals name="Running"/>
    <eLiterals name="InMaintenance" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true" eOpposite="#//Requirement/request"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//ApplicationInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" lowerBound="1"
        eType="#//Request" eOpposite="#//Request/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
